# Generated by Django 3.0 on 2020-09-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('brand_img', models.ImageField(blank=True, upload_to='brand_img', verbose_name='이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('delivery', models.CharField(choices=[('OD', 'OneDayDelivery'), ('REG', 'RegularDelivery')], default='OD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('FS', 'ForSale'), ('SS', 'StopSale'), ('SO', 'SoldOut')], default='FS', max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SellingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_company_name', models.CharField(blank=True, max_length=20, verbose_name='상호명')),
                ('_representative', models.CharField(blank=True, max_length=10, verbose_name='대표자')),
                ('_license_num', models.CharField(blank=True, max_length=100, verbose_name='사업자등록번호')),
                ('_mail_order_num', models.CharField(blank=True, max_length=100, verbose_name='통신판매업번호')),
                ('_biz_location', models.CharField(blank=True, max_length=100, verbose_name='사업장소재지')),
                ('_biz_hour', models.CharField(blank=True, max_length=255, verbose_name='영업시간')),
                ('_company_email', models.CharField(blank=True, max_length=255, verbose_name='메일')),
                ('_company_call', models.CharField(blank=True, max_length=255, verbose_name='전화번호')),
                ('model_size', models.TextField(blank=True, max_length=255, verbose_name='모델사이즈정보')),
                ('_shipping_info', models.TextField(blank=True, max_length=255, verbose_name='배송정보')),
                ('_exchange_refund_info', models.TextField(blank=True, max_length=255, verbose_name='교환/환불정보')),
                ('_product_notice', models.CharField(blank=True, max_length=100, verbose_name='상품정보고시')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('XS', 'X-SMALL'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], max_length=2)),
                ('color', models.CharField(blank=True, choices=[('WH', 'WHITE'), ('BL', 'BLACK'), ('GY', 'GRAY'), ('RD', 'RED'), ('BL', 'BLUE'), ('GR', 'GREEN'), ('YL', 'YELLOW'), ('PP', 'PURPLE'), ('BR', 'BROWN'), ('etc', 'etc')], max_length=3)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='info_img', verbose_name='이미지')),
                ('product_info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductInfo', verbose_name='상품정보이미지')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='main_img', verbose_name='이미지')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='상품이미지')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
    ]
