# Generated by Django 3.0 on 2020-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_cate',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
