# Generated by Django 3.0 on 2020-08-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.CharField(blank=True, choices=[('1', 'OneDayDelivery'), ('2', 'RegularDelivery')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'ForSale'), ('2', 'StopSale'), ('3', 'SoldOut')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.CreateModel(
            name='ProductInfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='이미지')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='상품정보이미지')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='이미지')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='상품이미지')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_company_name', models.CharField(blank=True, max_length=20, verbose_name='상호명')),
                ('_representative', models.CharField(blank=True, max_length=10, verbose_name='대표자')),
                ('_license_num', models.CharField(blank=True, max_length=100, verbose_name='사업자등록번호')),
                ('_mail_order_num', models.CharField(blank=True, max_length=100, verbose_name='통신판매업번호')),
                ('_biz_location', models.CharField(blank=True, max_length=100, verbose_name='사업장소재지')),
                ('customer_service', models.TextField(blank=True, max_length=255, verbose_name='스토어고객센터')),
                ('model_size', models.TextField(blank=True, max_length=255, verbose_name='모델사이즈정보')),
                ('shipping_info', models.TextField(blank=True, max_length=255, verbose_name='배송정보')),
                ('exchange_refund_info', models.TextField(blank=True, max_length=255, verbose_name='교환/환불정보')),
                ('product_notice', models.CharField(blank=True, max_length=100, verbose_name='상품정보고시')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
