# Generated by Django 3.0 on 2020-08-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200831_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderInfo',
            new_name='SellerInfo',
        ),
    ]
