# Generated by Django 3.0 on 2020-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200909_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinginfo',
            name='_company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='상호명'),
        ),
        migrations.AlterField(
            model_name='sellinginfo',
            name='_representative',
            field=models.CharField(blank=True, max_length=20, verbose_name='대표자'),
        ),
    ]
