# Generated by Django 3.0 on 2020-10-05 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200909_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='products.Product'),
        ),
    ]
