# Generated by Django 3.0 on 2020-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200831_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.CharField(blank=True, choices=[('OD', 'OneDayDelivery'), ('REG', 'RegularDelivery')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('FS', 'ForSale'), ('SS', 'StopSale'), ('SO', 'SoldOut')], default='1', max_length=2),
        ),
    ]
