# Generated by Django 3.0 on 2020-09-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200831_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerInfo',
            new_name='SellingInfo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
    ]
