# Generated by Django 3.0 on 2020-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200901_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellinginfo',
            old_name='customer_service',
            new_name='_customer_service',
        ),
        migrations.RenameField(
            model_name='sellinginfo',
            old_name='exchange_refund_info',
            new_name='_exchange_refund_info',
        ),
        migrations.RenameField(
            model_name='sellinginfo',
            old_name='product_notice',
            new_name='_product_notice',
        ),
        migrations.RenameField(
            model_name='sellinginfo',
            old_name='shipping_info',
            new_name='_shipping_info',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
