# Generated by Django 3.0 on 2020-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200902_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='detail',
            new_name='text',
        ),
        migrations.AddField(
            model_name='brand',
            name='intro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
