# Generated by Django 3.0 on 2020-08-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='images',
            field=models.ImageField(upload_to='events', verbose_name='이벤트이미지'),
        ),
    ]
