# Generated by Django 3.0 on 2020-09-09 08:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0003_auto_20200909_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=16)),
                ('address1', models.CharField(max_length=64)),
                ('address2', models.CharField(max_length=64)),
                ('phoneNum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
