# Generated by Django 3.0 on 2020-10-05 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201005_1129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderDate',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phoneNum',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_request',
            field=models.CharField(blank=True, max_length=250, verbose_name='배송요청사항'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default='null', max_length=250, verbose_name='주소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='detail_destination',
            field=models.CharField(default='null', max_length=250, verbose_name='상세주소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=250, verbose_name='이메일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='결제 예상금액'),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('NAVER', '네이버페이'), ('CACAO', '카카오페이'), ('TOSS', '토스'), ('CREDIT', '신용카드'), ('BANKBOOK', '무통장입금'), ('PHONE', '휴대폰결제')], default='NAVER', max_length=100, verbose_name='결제 수단'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='010-0000-0000', max_length=250, region=None, verbose_name='휴대폰'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='point_use',
            field=models.PositiveIntegerField(default=0, verbose_name='포인트 사용'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='010-0000-0000', max_length=128, region=None, verbose_name='수령인_휴대폰'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_delivery_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='배송비'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='상품금액'),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='00000', max_length=250, verbose_name='우편번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.CharField(max_length=50, verbose_name='수령인'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductOption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
