# Generated by Django 3.0 on 2020-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200818_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='primary',
            field=models.BooleanField(default=False, help_text='기본 배송지'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
